# Generated by Django 4.2.5 on 2023-09-15 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_alter_user_photo_userconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23a3e62b-75db-4c3d-8890-ab97be78fea9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23a3e62b-75db-4c3d-8890-ab97be78fea9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
