# Generated by Django 4.2.5 on 2023-09-27 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d77fe08-1c28-44ee-a6f6-51a67a899f1d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d77fe08-1c28-44ee-a6f6-51a67a899f1d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
