# Generated by Django 4.2.5 on 2023-09-27 05:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0124d77f-eda4-4287-8941-74904c96b5ec'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0124d77f-eda4-4287-8941-74904c96b5ec'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
