# Generated by Django 4.2.5 on 2023-10-05 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eb2cba3f-bb88-4449-8a5c-32c84f8bd68a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eb2cba3f-bb88-4449-8a5c-32c84f8bd68a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
